### ISSUE TITLE
Dot product or element wise product of Vc and Vw?

### ISSUE THREAD

**Issue by mazicwong** [AaronTengDeChuan/MLWA-Chinese-SLU#2]
Hi, it is a good job! Though I have a small question.

Seems that you use element wise product of Vc and Vw in the `class BilinearLayer(nn.Module):`.

While in Figure1 (c) in the paper, it is described as dot product?

Is my understanding of the details wrong? Wait for your reply, thanks~

**Comment by mazicwong** [comment]
Ex.

`class BilinearLayer(nn.Module):` is located in `MLWA-Chinese-SLU/src/components/layers.py`

**Comment by AaronTengDeChuan** [comment]
@mazicwong In fact, the dot product of two 1-dimension vectors can be implemented by first element-wise producting these two vectors and then summing all elements in the resulted vector.

**Comment by mazicwong** [comment]
Got it, thanks!

**Comment by hrwise-nlp** [comment]
hello, nice work. I am wondering did u try just concat the two vectors without adapter?
