### ISSUE TITLE
请问应该使用什么参数才可以得到你的论文复现结果呢

### ISSUE THREAD

**Issue by 1053399472** [AaronTengDeChuan/MLWA-Chinese-SLU#4]
`-dd
data/cais_bies-True_token-hanlp
-sd
test
-bs
16
-dr
0.3
-ced
128
-wed
128
-ehd
512
-aod
128
-sed
32
-sdhd
64`
使用这种参数得到的效果是Accepted performance: (0.8764241893076249, 0.9466403162055336, 0.8527667984189723) at test dataset;

**Comment by AaronTengDeChuan** [comment]
由于随机化的影响，在不同的硬件上可能需要不同的随机种子甚至参数才能达到相似的效果。
另外，分词使用的是 哈尔滨工业大学-社会计算与信息检索研究中心 推出的语言技术平台 ([Language Technology Platform, LTP](http://ltp.ai/))中的分词模型。也就是说，您需要在调用 ablation_study.sh 时将 tokenizer 参数指定为 “ltp”，详细接口请仔细阅读 ablation_study.sh 脚本代码。
