### ISSUE TITLE
请问ECDT-NLU数据集中的1033测试数据在哪里呀，从会议官网只能找到训练集

### ISSUE THREAD

**Issue by 1053399472** [AaronTengDeChuan/MLWA-Chinese-SLU#5]
如题

**Comment by zsc19** [comment]
同问
![image](https://user-images.githubusercontent.com/53292744/159453956-aa1bea6e-a419-49d2-b0bd-50b829f16149.png)

**Comment by AaronTengDeChuan** [comment]
你好，ECDT-NLU这个数据集，只有训练集和测试集。由于这个数据集被用于一个公开评测中，所以测试集不能公开。
您可以将训练集切分成训练集和验证集，报告在验证集上的结果。也可以使用N-Fold交叉验证得到表现最好的超参数，然后采用这个超参数对完整的训练集进行训练得到最终模型。只需要保证我们的模型和您的模型使用相同的切分方式。
